CREATE TABLE feature_toggles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_name text UNIQUE NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

INSERT INTO feature_toggles (feature_name, is_enabled) VALUES
    ('Attendance', true),
    ('Finance', true),
    ('Student Report', true),
    ('Attendance Report', true),
    ('Chapter Progress', true),
    ('Parent Login Access', true),
    ('Tests & Marks', true);
