CREATE TABLE fees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    center_id uuid NOT NULL REFERENCES centers(id) ON DELETE CASCADE,
    amount numeric NOT NULL,
    month date NOT NULL,
    status text NOT NULL CHECK (status IN ('Paid', 'Unpaid', 'Pending')),
    due_date date NOT NULL,
    remarks text,
    created_at timestamptz DEFAULT now() NOT NULL
);
